build(setup.py): re-order deps to avoid incompatibilities
Rather than one of the many more heavyweight python environment
management tools (e.g., conda, pyenv, poetry), we just use pip with
Fonduer. However, pip does not have a robust dependency resolver [1].
Instead, pip install dependencies in a recursive, serial loop. No effort
is made to ensure that the dependencies of all packages are fulfilled
simultaneously.

In Fonduer, we have a dependency on snorkel and emmental. Snorkel has
stricter requirements than emmental, so, when emmental is installed
first, we get the error below.

    ERROR: snorkel 0.9.5 has requirement scikit-learn<0.22.0,>=0.20.2, but you'll have scikit-learn 0.22.2.post1 which is incompatible.
    ERROR: snorkel 0.9.5 has requirement tensorboard<2.0.0,>=1.14.0, but you'll have tensorboard 2.2.0 which is incompatible.

We get this error despite there being compatible versions between
snorkel and emmental (scikit-learn==0.21.0 and tensorboard==1.15.0). So,
due to the recursive, serial loop that pip uses, we can resolve these
errors by installing snorkel, which has stricter dependencies, before
emmental.

[1]: https://github.com/pypa/pip/issues/988#issuecomment-552674491